language: java
sudo: false
install: true

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "nroduit-github"
    token:
      secure: "9208846583f27b7dd511895327f5e4e078ff1300"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
